### ISSUE TITLE
Event listeners for current selection

### ISSUE THREAD

**Issue by bmd-jpreiksa** [Jhsmit/ipymolstar#15]
Is there a way to extract current selection and not just mouse events?

**Comment by Jhsmit** [comment]
by selections do you mean created by Selection Mode (mouse cursor icon)?
I don't think thats possible. There was an issue about that on pdbe-molstar: https://github.com/molstar/pdbe-molstar/issues/85

What is possible (but not yet implemented) is to capture click events, if that helps I can up it in the priority list

**Comment by bmd-jpreiksa** [comment]
Thanks for quick reply,
Unfortunately, yes, Selection Mode listener  is the main functionality I
was lacking.
However, mouse click listener would be the next best option.
Thanks in advance

Kind regards,

J.P.

**Comment by Jhsmit** [comment]
I've added click events in v0.0.9.

example here: https://github.com/Jhsmit/ipymolstar/blob/master/examples/click_events.py
on pycafe: https://py.cafe/jhsmit/ipymolstar-click-interaction
