### ISSUE TITLE
Initialize `spin`

### ISSUE THREAD

**Issue by manzt** [Jhsmit/ipymolstar#3]
Trying out the demo, I notice that `spin` is only triggered on change. So if you were to:

```py
view = PDBeMolstar(
    molecule_id="1qyn",
    theme="light",
    hide_water=True,
    visual_style="cartoon",
)
view.spin = True
view
```

the viewer wouldn't be spinning. I'm not sure if this is something that can be set in initial options:

https://github.com/Jhsmit/ipymolstar/blob/825c753d36f77eee57199815542f6243b3e43885/src/ipymolstar/widget.js#L109

or must be set initially. Great work!

**Comment by Jhsmit** [comment]
yes indeed, I ran into the issue as well. 
in the pdbe-molstar [docs](https://github.com/molstar/pdbe-molstar/wiki/1.-PDBe-Molstar-as-JS-plugin) there is no mention of passing spin as initial option

I can't find the example now but I think its possible to register some kind of callback to be executed after the rendering of the viewer

```js
viewerInstance.render(viewerContainer, options).then((viewerInstance) => {
  viewerInstance.visual.toggleSpin(model.get('spin'))
});

```

(this is what codeium suggests)
