### ISSUE TITLE
Ploomber demo site not working

### ISSUE THREAD

**Issue by pierrepo** [Jhsmit/ipymolstar#7]
Hello,

It looks like the Ploomber demo site (https://purple-glade-1760.ploomberapp.io/) is not working. The link leads to an authentication page at Ploomber, that eventually shows an empty dashboard-like page:

![image](https://github.com/Jhsmit/ipymolstar/assets/733861/861674d0-1316-4390-8b4d-612ec3c7bd68)

Do you have any idea how I could run the demo at Ploomber?

**Comment by Jhsmit** [comment]
Hi, thanks for the heads up. I've restarted the demo here: https://hidden-resonance-5816.ploomberapp.io
