### ISSUE TITLE
support load local pdb file

### ISSUE THREAD

**Issue by dsxksss** [Jhsmit/ipymolstar#9]
hi @Jhsmit, can it support reading local files to display this feature? I think this feature is handy 😀

**Comment by dsxksss** [comment]
Thank you, I think i know how to do it,  please write it in README so that more people can see it. that would be great  ❤️😍

**Comment by dsxksss** [comment]
Thank you, I think i know how to do it 😁

**Comment by dsxksss** [comment]
Thank you, if it can support reading the current user's files, that would be great, just like using "./x.pdb" 😁

**Comment by Jhsmit** [comment]
It should be possible, in https://github.com/molstar/pdbe-molstar/issues/95 is a proposed solution:
 `var url = URL.createObjectURL(new Blob([pdb_str]));` then use `url in custdomData~`

also here is discussion with a link to a stakoverflow explaining how to encode the structure in a byte64 url:
https://github.com/molstar/pdbe-molstar/issues/86

I'll try to find some time to include it, it is certainly a frequent use case, I also need it myself

**Comment by Jhsmit** [comment]
it's not possible yet, but I'll add it in version 0.0.4

**Comment by dsxksss** [comment]
Thank you for adopting my issues :)

**Comment by Jhsmit** [comment]
now added in ipymolstar v 0.0.4, let me know if there are any issues/questions!

**Comment by dsxksss** [comment]
Thank you so much :) ❤

**Comment by dsxksss** [comment]
For the new feature of local files, I think we can encapsulate some details of usage and use it like this


``` py
from ipymolstar import PDBeMolstar
from pathlib import Path
import os

def create_custom_data(path:str, is_binary:bool):
    file_path = Path(path).resolve()
    
    if not file_path.exists():
        raise FileNotFoundError(f"No file found at {file_path}")

    data = file_path.read_bytes() if is_binary else file_path.read_text()
    
    return {
        'data': data,
        'format': file_path.suffix.lstrip('.'),
        'binary': is_binary
    }

view = PDBeMolstar(
    custom_data=create_custom_data(os.path.join(,'test_files','5ggs.pdb'),False) 
)
view
```


I hope that it can be installed and used as soon as possible. Of course, I can also implement it with in my project, but I still want to see your opinion first 🤔

**Comment by Jhsmit** [comment]
Hi, I like the suggestion, I was also thinking about other helper methods we could add such as converting tabular data into residue-coloring data. 

You can pass the data both as bytes or strings (`read_bytes` and `read_text`) both work, the binary flag is only needed if your data file is binary, for example for `bcif` files.
